### ISSUE TITLE
Module not found/doesn't match local path

### ISSUE THREAD

**Issue by wad3g** [dliv/react-starter#1]
```
import DashboardPage from './pages/Dashboard';
import ExampleOtherPage from './pages/Other';
```

Updating the casing for `'./pages/dashboard'` and `'./pages/other'` fixes it. 

You already need a yugs label for this guy?

**Comment by dliv** [comment]
More like a "works-on-my-machine" label. Kidding, good catch. Maybe I did a case only file rename without using `git mv`. I'll fix today.

What are your thoughts on these PascalCase and camelCase file names? That's taken from `react-create-app`. I've preferred kebab-case in the past to avoid issues like this.

**Comment by wad3g** [comment]
Kebab-case all the way, but the having `dashboard` and `other` the only lower case drives me a little crazy. 

Especially right next to `Header`.

Would FB use PascalCase on the actual `.jsx` files for dashboard and other?

**Comment by dliv** [comment]
Not sure, at first I thought they only used it for components like `App.js` to make them stand out, but notice `registerServiceWorker` is camelCase and not a component. I don't think `create-react-app` is meant to be prescriptive re. naming conventions, but I'm also hesitant to change the casing without good reason because it makes it slightly more difficult to see how this project relates to `create-react-app`.
